[package]
name = "thundos"
version = "0.1.0"
authors = ["Don Reilly <dreilly1982@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1"
volatile = "0.1.0"
spin = "0.4.5"
bitflags = { version="0.4.0", features=["no_std"]}